### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by ghost** [czp3009/danmuji#1]
弹幕姬目前的UI可以改进一下，然后加个设置菜单。
设置可包含：是否显示系统信息（例如赠送小电视会在全站的直播间弹出信息，这个信息也会在弹幕姬上呈现）
不同类型的弹幕（文字，礼物，不同用户）的字体颜色和大小
还有……
算了不写了，CZP要打死我

**Comment by czp3009** [comment]
看来还得加一个配置文件，过段时间我写一下

**Comment by czp3009** [comment]
在最新版本中已完成此功能 https://github.com/czp3009/danmuji/releases/tag/v1.2
