### ISSUE TITLE
堵塞？

### ISSUE THREAD

**Issue by yjqiang** [czp3009/danmuji#3]
请问这个弹幕获取是实时的吗？是堵塞的么？没有延迟以及丢包问题？

**Comment by czp3009** [comment]
弹幕是通过连接弹幕推送服务器得到的(socket), 只要 socket 里面一有数据就会显示(服务端分发弹幕本身会有延迟, 高峰期大概五秒).

读 socket 是异步的, 不是阻塞的.

延迟主要来自服务器本身的处理时间和网络时延, 丢包是存在的, 主要由网络问题引起, 这是无法解决的.

如果想看 socket 部分的读取的话, 可以看我的[另一个项目的源码](https://github.com/czp3009/bilibili-api).
